(change-db) feat: find config file from every folder in the project

diff --git a/scripts/ec/change-db b/scripts/ec/change-db
--- a/scripts/ec/change-db
+++ b/scripts/ec/change-db
@@ -13,8 +13,8 @@ source "$DOTLY_PATH/scripts/core/_main.sh"
 ##?   change-db <dbName> [--regendb] [--styles]
 docs::parse "$@"
 
-
-FILE=$(find . -name "database.php" -not -path "./**/testing/*")
+ROOT_CONTENT=$(git rev-parse --show-toplevel)
+FILE=$(find $ROOT_CONTENT -name "database.php" -not -path "*/testing/*")
 
 if [ -f "$FILE" ]; then
     numFileDatabase="$(grep -En "^[\$]db\[[\"']default[\"']\]\[[\"']database[\"']\]" $FILE | head -n 1 | cut -d: -f1)"
@@ -27,6 +27,6 @@ if [ -f "$FILE" ]; then
     echo ""
     echo "💾 Database changed correctly to $dbName"
 else
-    >&2 echo "🏚 Database config file not found. Make sure you are inside the project."
+    >&2 echo "🏚 Database config file not found. Make sure you are inside the project folder."
 fi
 
